# This workflow will deploy a DotNet project

name: DotNet CD

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/poi/web
    env:
      REGISTRY: openhackufq2qk03acr.azurecr.io
      IMAGE_NAME: devopsoh/api-poi
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ACR
        uses: docker/login-action@v1 
        with:
          registry: ${{env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{env.REGISTRY }}/${{env.IMAGE_NAME }}:${{ github.sha }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
