on: [push, pull_request]
name: Test Trips API
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install git
        run: apt update && apt install git gcc -y
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
        working-directory: apis/trips
